name: Testing

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: enable
        name: Enable Toolchain
        run: corepack enable

      - id: setup
        name: Setup Toolchain
        run: yarn install

      - id: format
        name: Run Formatting-Checks
        run: yarn lint

      - id: check
        name: Run Build Checks
        run: yarn check

  unit:
    name: Units
    runs-on: ubuntu-latest
    needs: check

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: enable
        name: Enable Toolchain
        run: corepack enable

      - id: setup
        name: Setup Toolchain
        run: yarn install

      - id: build
        name: Build Project
        run: yarn build

      - id: test
        name: Run Unit Tests
        run: yarn test:unit

  integration:
    name: Integration
    runs-on: ubuntu-latest
    needs: unit

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: enable
        name: Enable Toolchain
        run: corepack enable

      - id: setup
        name: Setup Toolchain
        run: yarn install

      - id: integration
        name: Setup Integration Toolchain
        run: yarn run playwright install --with-deps

      - id: test
        name: Run Integration Tests
        run: yarn test:integration
